application: ebcmdev
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /themes
  static_dir: templates/themes

- url: /static
  static_dir: static

- url: /.*
  script: guestbook6_templates.py

skip_files:
- ^(.*/)(dev).py
